sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_3beeaf392928_key -iv $encrypted_3beeaf392928_iv -in multi-k8s-273804-9bc7f2697a86.json.enc -out multi-k8s-273804-9bc7f2697a86.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-273804
  - gcloud config set compute/zone us-central1-c	
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t agustisa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true agustisa/docker-react npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master